<?php

/**
 * PlugindvbNewsletterLanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugindvbNewsletterLanguageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugindvbNewsletterLanguageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugindvbNewsletterLanguage');
    }
}