<?php

/**
 * PlugindvbNewsletterSubscriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugindvbNewsletterSubscriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugindvbNewsletterSubscriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugindvbNewsletterSubscription');
    }
}