generator:
  class: sfDoctrineGenerator
  param:
    model_class:           dvbNewsletterList
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              list
    plural:                lists
    route_prefix:          dvb_newsletter_admin_list
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: 'Lists'
        display: [=name,created_at,updated_at]
      filter:  ~
      form:
        display: [name,description, language_id,default_format,visibility,enabled]
      edit:    ~
      new:
        title: 'Create a new list'
