# $Id$
# 
# The MIT License
#
# Copyright (c) 2010 Davide Bellettini <davide@davidebellettini.it>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

options:
  charset: utf8
  collate: utf8_general_ci

dvbNewsletterList:
  columns:
    id:
      type: integer(4)
      unsigned: true
      autoincrement: true
      primary: true
    name:
      type: string(255)
      notnull: true
  relations:
    Subscribers:
      foreignAlias: Newsletters
      class: Subscriber
      refClass: NewsletterSubscriber
  actAs:
    Timestampable: ~     
      
dvbNewsletterSubscriber:
  columns:
    id:
      type: integer(4)
      unsigned: true
      autoincrement: true
      primary: true
    email:
      type: string(255)
      notnull: true
      unique: true
  actAs:
    Timestampable: ~
      
dvbNewsletterListSubscriber:
  options:
    symfony:
      form: false
      filter: false
  columns:
    dvb_newsletter_list_id:
      type: integer(4)
      unsigned: true
      primary: true
    dvb_newsletter_subscriber_id:
      type: integer(4)
      unsigned: true
      primary: true
  relations:
    dvbNewsletterList:
      foreignAlias: NewsletterSubscribers
      onDelete: 'NO ACTION'
      onUpdate: CASCADE
    dvbNewsletterSubscriber:
      foreignAlias: NewsletterSubscribers
      onDelete: CASCADE
      onUpdate: CASCADE
  actAs:
    Timestampable: ~
       